# -*- coding: utf-8 -*-
"""dayana.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QF6AD6y2zy4RhwdHpBIJ8IjtWDyKQ7z9
"""

#.autor dayana

import math

# Coordenadas del primer punto (x, y)
fila_pepito = float(input("Ingrese la fila de pepito: "))
columna_pepito = float(input("Ingrese la columna de pepito: "))

# Coordenadas del segundo punto (x, y)
fila_maria = float(input("Ingrese la fila de maria: "))
columna_maria = float(input("Ingrese la columna de maria: "))

# Cálculo de la distancia
distancia = math.sqrt((fila_maria - fila_pepito) ** 2 + (columna_maria - fila_pepito) ** 2)

# Mostrar el resultado
print("pepito esta a", distancia, "cuadras de maria.")